# Generated by Django 3.2.7 on 2023-04-03 06:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_fname', models.CharField(max_length=200)),
                ('agent_lname', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('phone_number2', models.IntegerField(blank=True, null=True)),
                ('agent_email', models.EmailField(max_length=254)),
                ('home_address1', models.CharField(max_length=500)),
                ('home_address2', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(choices=[('abuja', 'Abuja'), ('abia', 'Abia'), ('adamawa', 'Adamawa'), ('anambra', 'Anambra'), ('akwa Ibom', 'Akwa Ibom'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross River', 'cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nassarawa', 'Nassarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('homeImg', models.ImageField(blank=True, default='Profile-Photo-Place-Holder.PNG', null=True, upload_to='home_img')),
                ('elec_water', models.CharField(default='Stable Electricity and Water', max_length=200)),
                ('distance', models.CharField(default='200 meters from school', max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Profile-Photo-Place-Holder.png', upload_to='profile_pics')),
                ('uni_level', models.CharField(choices=[('100L', '100L'), ('200L', '200L'), ('300L', '300L'), ('400L', '400L'), ('500L', '500L')], default='100L', max_length=200)),
                ('phone_number', models.IntegerField(null=True)),
                ('email', models.EmailField(default='egwusamuel2015@gmail.com', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pop_searched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge_name', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('date_created', models.DateTimeField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LodgeProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorrounding', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('lodge_interior', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('roomFront', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('roomBack', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('roomKitchen', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('roomToiletBath', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('bedRoom', models.ImageField(blank=True, null=True, upload_to='home_img')),
                ('roomsTotalNum', models.PositiveSmallIntegerField()),
                ('roomsAvailable', models.PositiveSmallIntegerField()),
                ('lodge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lodges.lodge')),
            ],
        ),
        migrations.CreateModel(
            name='AgentProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge_name', models.CharField(max_length=200, null=True)),
                ('homeImg', models.ImageField(default='Profile-Photo-Place-Holder.png', upload_to='agent_img')),
                ('sorrounding', models.ImageField(default='Profile-Photo-Place-Holder.png', upload_to='agent_img')),
                ('lodge_interior', models.ImageField(default='Profile-Photo-Place-Holder.png', upload_to='agent_img')),
                ('roomFront', models.ImageField(default='Profile-Photo-Place-Holder.png', upload_to='agent_img')),
                ('roomBack', models.ImageField(default='Profile-Photo-Place-Holder.png', upload_to='agent_img')),
                ('roomKitchen', models.ImageField(default='Profile-Photo-Place-Holder.png', upload_to='agent_img')),
                ('roomToiletBath', models.ImageField(default='Profile-Photo-Place-Holder.png', upload_to='agent_img')),
                ('bedRoom', models.ImageField(default='Profile-Photo-Place-Holder.png', upload_to='agent_img')),
                ('price', models.FloatField()),
                ('elec_water', models.CharField(default='Stable Electricity and Water', max_length=200)),
                ('distance', models.CharField(default='200 meters from school', max_length=200)),
                ('roomsTotalNum', models.PositiveSmallIntegerField()),
                ('roomsAvailable', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('agent_ersonal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lodges.agentpersonalinfo')),
            ],
        ),
    ]
