# Generated by Django 3.2.7 on 2023-04-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentproperties',
            name='agent_ersonal_info',
        ),
        migrations.DeleteModel(
            name='AgentPersonalInfo',
        ),
        migrations.DeleteModel(
            name='AgentProperties',
        ),
    ]
