# Generated by Django 3.2.7 on 2023-02-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodges', '0002_pop_searched'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pop_searched',
        ),
    ]
